// TEST_OUTPUT must contain the app's html-to-image.js and html2canvas.js versions.
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const runtime=process.env.USERPROFILE+'/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium}=require(runtime+'/playwright'),{PNG}=require(runtime+'/pngjs');
const root=path.resolve(__dirname,'..'),out=process.env.TEST_OUTPUT;
const close=(a,b)=>assert.ok(Math.abs(a-b)<.02,`${a} != ${b}`);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe'});try{
const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>{errors.push(d.message());return d.dismiss()});
await page.route('https://**/*',r=>{const u=r.request().url(),f=u.includes('/html-to-image@')?'html-to-image.js':u.includes('/html2canvas@')?'html2canvas.js':null;return f?r.fulfill({path:path.join(out,f)}):r.abort()});
const js=fs.readFileSync(path.join(root,'app.js'),'utf8').replace('\ninit();','\nwindow.glassTest={state,assets,createBlock,refreshSlots,applyGlobalText,applyParagraphStyle,relayout,renderBackground,openParagraphInspector,prepareOutputClone,readHighlightData};\ninit();');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('href="styles.css"',`href="${pathToFileURL(path.join(root,'styles.css')).href}"`).replace('<script src="app.js"></script>',()=>'<script>'+js.replace(/<\/script/gi,'<\\/script')+'</script>');
const harness=path.join(out,'glass.html');fs.writeFileSync(harness,html);await page.goto(pathToFileURL(harness).href);await page.waitForSelector('#canvas .editable');
const measure=()=>page.evaluate(()=>{const b=document.querySelector('#canvas .paragraph-block'),ed=b.querySelector('.editable'),s=getComputedStyle(ed),layer=b.querySelector('.paragraph-glass');return {font:parseFloat(s.fontSize),padding:[s.paddingTop,s.paddingRight,s.paddingBottom,s.paddingLeft].map(parseFloat),width:b.offsetWidth,layerWidth:layer?.offsetWidth,height:b.offsetHeight,canvas:document.querySelector('#canvas').offsetHeight,override:JSON.parse(b.dataset.paragraphOverride||'{}'),html:ed.innerHTML,text:ed.textContent,layerHidden:layer?.hidden,alpha:layer?.style.backgroundColor}});
const open=()=>page.evaluate(()=>glassTest.openParagraphInspector(document.querySelector('#canvas .paragraph-block')));
const input=async(id,value)=>page.locator('#'+id).evaluate((e,value)=>{e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}))},value);
await page.locator('#canvas .editable').fill('짧은 문장');const base=await measure();await open();assert.equal(await page.locator('#paragraphGlassOpacity').isDisabled(),true);
await page.locator('#paragraphGlassEnabled').check();let m=await measure();close(m.font,15.48);m.padding.forEach(v=>close(v,36.12));assert.equal(m.width,516);assert.equal(m.layerWidth,516);assert.equal(await page.locator('#paragraphUseDefault').isChecked(),true);assert.equal(await page.locator('#paragraphFontSize').isDisabled(),true);
await page.locator('#paragraphUseDefault').uncheck();await page.locator('#paragraphFontSize').fill('32');m=await measure();close(m.font,27.52);assert.equal(m.override.glass.enabled,true);await input('paragraphGlassOpacity',63);assert.equal((await measure()).override.fontSize,32);
await page.locator('#paragraphUseDefault').check();m=await measure();assert.equal(m.override.fontSize,undefined);assert.equal(m.override.glass.opacity,63);close(m.font,15.48);
await page.locator('#paragraphGlassEnabled').uncheck();m=await measure();assert.equal(m.font,18);assert.deepEqual(m.padding,base.padding);assert.equal(m.height,base.height);assert.equal(m.canvas,base.canvas);
await page.locator('#paragraphGlassEnabled').check();await page.locator('#closeInspector').click();await input('padX',60);m=await measure();close(m.font,14.4);m.padding.forEach(v=>close(v,48));assert.equal(m.width,480);await input('padX',42);await input('fontSize',24);close((await measure()).font,20.64);await input('fontSize',18);
await open();for(const opacity of [0,100,35]){await input('paragraphGlassOpacity',opacity);m=await measure();assert.equal(m.override.glass.opacity,opacity);assert.equal(await page.locator('#canvas .editable').evaluate(e=>getComputedStyle(e).opacity),'1');}await page.locator('#closeInspector').click();
await page.evaluate(()=>{const t=glassTest,l=document.querySelector('#blockList'),b=l.querySelector('.paragraph-block');b.querySelector('.editable').innerHTML='<b>유리 문단</b> <span style="background-color:#ffe27a">'+('여러 줄 강조 표시와 문단 레이아웃 ').repeat(18)+'</span>';const p=t.createBlock('paragraph');p.querySelector('.editable').textContent='다음 문단';p.dataset.paragraphOverride=JSON.stringify({fontSize:32,glass:{enabled:true,opacity:45}});l.append(p);for(const side of ['left','right']){const bubble=t.createBlock('bubble',side);bubble.querySelector('.editable').textContent=('말풍선 높이와 줄바꿈 검증 ').repeat(8);l.append(bubble);}t.refreshSlots();t.applyGlobalText();t.relayout();});
const text=(await measure()).html;
await page.evaluate(()=>{const t=glassTest,b=document.querySelector('#canvas .paragraph-block');b.dataset.paragraphOverride=JSON.stringify({glass:{enabled:false,opacity:35}});t.applyParagraphStyle(b);t.relayout()});const off=await measure();
await page.evaluate(()=>{const t=glassTest,b=document.querySelector('#canvas .paragraph-block');b.dataset.paragraphOverride=JSON.stringify({glass:{enabled:true,opacity:35}});t.applyParagraphStyle(b);t.relayout()});m=await measure();assert.equal(m.html,text);assert.ok(m.height>off.height);assert.ok(m.canvas>off.canvas);
await page.evaluate(()=>{const t=glassTest,bs=[...document.querySelectorAll('#canvas .content-block')],gap=t.state.fontSize*t.state.lineHeight;for(let i=1;i<bs.length;i++)if(Math.abs(bs[i].offsetTop-bs[i-1].offsetTop-bs[i-1].offsetHeight-gap)>1)throw Error('block gap changed');const b=bs[0],ed=b.querySelector('.editable'),before=t.readHighlightData(ed);t.applyParagraphStyle(b);const after=t.readHighlightData(ed);if(JSON.stringify(before.ranges)!==JSON.stringify(after.ranges)||before.text!==after.text)throw Error('semantic offsets changed');});
// Exercise uploaded fonts with the real UI and retain the font for both PNG engines.
await page.locator('#fontUpload').setInputFiles('C:/Windows/Fonts/arial.ttf');await page.waitForFunction(()=>document.querySelector('#fontFamily').value.startsWith('custom-'));assert.ok(await page.locator('#canvas .editable').first().evaluate(e=>e.style.fontFamily.includes('UserFont_')));
await page.evaluate(()=>{const t=glassTest,c=document.createElement('canvas');c.width=320;c.height=240;const x=c.getContext('2d');x.fillStyle='#204080';x.fillRect(0,0,320,240);x.fillStyle='#b04020';for(let y=0;y<240;y+=24)x.fillRect(0,y,320,12);t.assets.bgImage=c.toDataURL();t.assets.leftProfile=t.assets.bgImage;t.assets.rightProfile=t.assets.bgImage;t.state.bg.x=130;t.state.bg.y=-90;t.state.bg.zoom=150;t.state.bg.blur=3;t.state.bg.brightnessByMode.image=-15;t.applyGlobalText();t.renderBackground();});
const original=await page.evaluateHandle(()=>window.htmlToImage);
for(const width of [1280,390]){await page.setViewportSize({width,height:900});await page.evaluate(()=>glassTest.relayout());await open();const rect=await page.locator('#bubbleInspector').boundingBox();assert.ok(rect.x>=0&&rect.x+rect.width<=width+.1);await page.screenshot({path:path.join(out,`glass-ui-${width}.png`)});await page.locator('#closeInspector').click();
for(const mode of ['solid','gradient','image']){await page.evaluate(mode=>{glassTest.state.bg.mode=mode;glassTest.state.bg.color='#204080';glassTest.state.bg.gradStart='#204080';glassTest.state.bg.gradEnd='#b04020';glassTest.renderBackground()},mode);
await page.locator(width===390?'#mobilePreviewBtn':'#btnSave').click();await page.waitForFunction(()=>!document.querySelector('#btnSave').disabled);
const geometry=await page.evaluate(()=>{const a=document.querySelector('#canvas .paragraph-block'),b=document.querySelector('.output-canvas .paragraph-block');return {a:[a.offsetWidth,a.offsetHeight,a.offsetTop],b:[b.offsetWidth,b.offsetHeight,b.offsetTop]}});assert.deepEqual(geometry.a,geometry.b);
for(const engine of ['primary','fallback']){await page.evaluate(({original,engine})=>{window.htmlToImage=engine==='primary'?original:{...original,toPng:()=>Promise.reject(Error('forced glass fallback')),toSvg:()=>Promise.reject(Error('forced glass fallback'))}}, {original,engine});
const download=page.waitForEvent('download');await page.locator('#previewDownload').click();const file=path.join(out,`glass-${width}-${mode}-${engine}.png`);await(await download).saveAs(file);assert.ok((await page.locator('.output-preview-note').textContent()).includes(engine==='primary'?'primary (html-to-image) 성공':'fallback (html2canvas) 성공'));
const png=PNG.sync.read(fs.readFileSync(file));assert.equal(png.width,1800);let yellow=0,ink=0;for(let i=0;i<png.data.length;i+=4){const [r,g,b]=png.data.slice(i,i+3);if(r>220&&g>170&&b<160)yellow++;if(r<90&&g<90&&b<90)ink++;}assert.ok(yellow>1000&&ink>1000,'highlight or text missing');
if(mode==='solid'){const at=(x,y)=>{const i=(y*png.width+x)*4;return [...png.data.slice(i,i+3)]};const background=at(15,180),panel=at(200,180),corner=at(127,133);assert.ok(panel.every((v,i)=>Math.abs(v-(background[i]*.65+255*.35))<3),'white tint alpha incorrect');assert.ok(corner.every((v,i)=>Math.abs(v-background[i])<5),'radius missing');}
console.log('PASS glass PNG',width,mode,engine,png.width,png.height);
}await page.locator('#previewBack').click();await page.evaluate(original=>window.htmlToImage=original,original);
}}
assert.deepEqual(errors,[]);console.log('PASS independent overrides, full width, padding, font scaling, OFF restoration, layout, highlights, custom font, desktop/mobile and both PNG engines');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
